#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# Narizgnaw：非常感谢KFERMercer大佬提供的OpenWrt-CI。

name: 云编译

on:
  push:
    branches: 
      - master
  schedule:
      - cron: 0 16 * * *
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
      - name: 清理系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
      - name: 更新软件列表
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
      - name: 安装编译所需环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
      - name: 进行安装后的清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          git clone https://github.com/tty228/luci-app-serverchan
          git clone https://github.com/rosywrt/luci-theme-rosy
          git clone https://github.com/tzxiaozhen88/luci-app-koolproxyR
          
      - name: 构建编译扩展环境
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 导入自定义配置
        run: |
          rm -f ./.config*
          touch ./.config
          # 编译32位x86固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_generic=y
          CONFIG_TARGET_x86_generic_Generic=y
          EOF
          
          # 设置固件大小:
          cat >> .config <<EOF
          # CONFIG_TARGET_KERNEL_PARTSIZE=16
          CONFIG_TARGET_ROOTFS_PARTSIZE=256
          EOF
          # 固件压缩:
          # cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_GZIP=y
          # EOF
          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          EOF
          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          EOF
          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          EOF
          # LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-accesscontrol=y
          # CONFIG_PACKAGE_luci-app-acme is not set
          # CONFIG_PACKAGE_luci-app-adblock is not set
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-advanced-reboot is not set
          # CONFIG_PACKAGE_luci-app-ahcp is not set
          # CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-arpbind=y
          # CONFIG_PACKAGE_luci-app-asterisk is not set
          # CONFIG_PACKAGE_luci-app-attendedsysupgrade is not set
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-bcp38 is not set
          # CONFIG_PACKAGE_luci-app-bird1-ipv4 is not set
          # CONFIG_PACKAGE_luci-app-bird1-ipv6 is not set
          # CONFIG_PACKAGE_luci-app-bmx6 is not set
          # CONFIG_PACKAGE_luci-app-bmx7 is not set
          # CONFIG_PACKAGE_luci-app-cifsd is not set
          # CONFIG_PACKAGE_luci-app-cjdns is not set
          # CONFIG_PACKAGE_luci-app-clamav is not set
          # CONFIG_PACKAGE_luci-app-commands is not set
          # CONFIG_PACKAGE_luci-app-cshark is not set
          # CONFIG_PACKAGE_luci-app-ddns is not set
          # CONFIG_PACKAGE_luci-app-diag-core is not set
          # CONFIG_PACKAGE_luci-app-dnscrypt-proxy is not set
          # CONFIG_PACKAGE_luci-app-dnsforwarder is not set
          # CONFIG_PACKAGE_luci-app-dnspod is not set
          # CONFIG_PACKAGE_luci-app-dump1090 is not set
          # CONFIG_PACKAGE_luci-app-dynapoint is not set
          # CONFIG_PACKAGE_luci-app-e2guardian is not set
          # CONFIG_PACKAGE_luci-app-familycloud is not set
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          # CONFIG_PACKAGE_luci-app-freifunk-diagnostics is not set
          # CONFIG_PACKAGE_luci-app-freifunk-policyrouting is not set
          # CONFIG_PACKAGE_luci-app-freifunk-widgets is not set
          # CONFIG_PACKAGE_luci-app-frpc is not set
          # CONFIG_PACKAGE_luci-app-fwknopd is not set
          # CONFIG_PACKAGE_luci-app-guest-wifi is not set
          # CONFIG_PACKAGE_luci-app-haproxy-tcp is not set
          CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-hnet is not set
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          # CONFIG_PACKAGE_luci-app-kodexplorer is not set
          # CONFIG_PACKAGE_luci-app-lxc is not set
          # CONFIG_PACKAGE_luci-app-meshwizard is not set
          CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-mjpg-streamer is not set
          # CONFIG_PACKAGE_luci-app-mtwifi is not set
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          # CONFIG_PACKAGE_luci-app-n2n_v2 is not set
          # CONFIG_PACKAGE_luci-app-netdata is not set
          # CONFIG_PACKAGE_luci-app-nft-qos is not set
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          # CONFIG_PACKAGE_luci-app-noddos is not set
          # CONFIG_PACKAGE_luci-app-nps is not set
          # CONFIG_PACKAGE_luci-app-ntpc is not set
          # CONFIG_PACKAGE_luci-app-ocserv is not set
          # CONFIG_PACKAGE_luci-app-olsr is not set
          # CONFIG_PACKAGE_luci-app-olsr-services is not set
          # CONFIG_PACKAGE_luci-app-olsr-viz is not set
          # CONFIG_PACKAGE_luci-app-openvpn is not set
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-p910nd is not set
          # CONFIG_PACKAGE_luci-app-pagekitec is not set
          # CONFIG_PACKAGE_luci-app-polipo is not set
          # CONFIG_PACKAGE_luci-app-pppoe-relay is not set
          # CONFIG_PACKAGE_luci-app-pptp-server is not set
          # CONFIG_PACKAGE_luci-app-privoxy is not set
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-qos is not set
          # CONFIG_PACKAGE_luci-app-radicale is not set
          CONFIG_PACKAGE_luci-app-ramfree=y
          # CONFIG_PACKAGE_luci-app-rp-pppoe-server is not set
          CONFIG_PACKAGE_luci-app-samba=y
          # CONFIG_PACKAGE_luci-app-samba4 is not set
          # CONFIG_PACKAGE_luci-app-shadowsocks-libev is not set
          # CONFIG_PACKAGE_luci-app-shairplay is not set
          # CONFIG_PACKAGE_luci-app-siitwizard is not set
          # CONFIG_PACKAGE_luci-app-simple-adblock is not set
          # CONFIG_PACKAGE_luci-app-smartdns is not set
          # CONFIG_PACKAGE_luci-app-softethervpn is not set
          # CONFIG_PACKAGE_luci-app-splash is not set
          CONFIG_PACKAGE_luci-app-sqm=y
          # CONFIG_PACKAGE_luci-app-squid is not set
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks is not set
          # CONFIG_PACKAGE_luci-app-ssrserver-python is not set
          # CONFIG_PACKAGE_luci-app-statistics is not set
          CONFIG_PACKAGE_luci-app-syncdial=y
          # CONFIG_PACKAGE_luci-app-tinyproxy is not set
          # CONFIG_PACKAGE_luci-app-transmission is not set
          # CONFIG_PACKAGE_luci-app-travelmate is not set
          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-udpxy is not set
          # CONFIG_PACKAGE_luci-app-uhttpd is not set
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          # CONFIG_PACKAGE_luci-app-unbound is not set
          CONFIG_PACKAGE_luci-app-upnp=y
          # CONFIG_PACKAGE_luci-app-usb-printer is not set
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_luci-app-verysync is not set
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          # CONFIG_PACKAGE_luci-app-vnstat is not set
          # CONFIG_PACKAGE_luci-app-vpnbypass is not set
          CONFIG_PACKAGE_luci-app-vsftpd=y
          # CONFIG_PACKAGE_luci-app-watchcat is not set
          # CONFIG_PACKAGE_luci-app-webadmin is not set
          # CONFIG_PACKAGE_luci-app-wifischedule is not set
          # CONFIG_PACKAGE_luci-app-wireguard is not set
          CONFIG_PACKAGE_luci-app-wol=y
          # CONFIG_PACKAGE_luci-app-wrtbwmon is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-app-zerotier=y
          EOF
          # 额外软件和主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-rosy=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          CONFIG_PACKAGE_luci-app-koolproxyR=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          EOF
          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_htop=y
          CONFIG_PACKAGE_wget=y
          CONFIG_PACKAGE_nano=y
          EOF
          
          # 取消默认的ddns插件:
          cat >> .config <<EOF
          CONFIG_PACKAGE_ddns-scripts is not set
          CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          CONFIG_PACKAGE_ddns-scripts_dnspod is not set
          EOF
          
          # 取消无线驱动:
          cat >> .config <<EOF
          # CONFIG_DRIVER_11AC_SUPPORT is not set
          # CONFIG_DRIVER_11N_SUPPORT is not set
          # CONFIG_DRIVER_11W_SUPPORT is not set
          # CONFIG_PACKAGE_ath9k-htc-firmware is not set
          # CONFIG_PACKAGE_hostapd-common is not set
          # CONFIG_PACKAGE_iw is not set
          # CONFIG_PACKAGE_kmod-ath is not set
          # CONFIG_PACKAGE_kmod-ath10k is not set
          # CONFIG_PACKAGE_kmod-ath5k is not set
          # CONFIG_PACKAGE_kmod-ath9k is not set
          # CONFIG_PACKAGE_kmod-ath9k-htc is not set
          # CONFIG_PACKAGE_kmod-cfg80211 is not set
          # CONFIG_PACKAGE_kmod-mac80211 is not set
          # CONFIG_PACKAGE_kmod-rt2800-usb is not set
          # CONFIG_PACKAGE_kmod-rt2x00-lib is not set
          # CONFIG_PACKAGE_rt2800-usb-firmware is not set
          # CONFIG_PACKAGE_wireless-regdb is not set
          # CONFIG_PACKAGE_wpad is not set
          EOF
          
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: 下载编译所需源码
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: 进行固件编译
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          
      - name: 准备文件
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name : 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
