#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# Narizgnaw：非常感谢KFERMercer大佬提供的OpenWrt-CI。

name: 云编译

on:
  push:
    branches: 
      - master
  schedule:
      - cron: 0 16 * * *
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
      - name: 清理系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
      - name: 更新软件列表
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
      - name: 安装编译所需环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install linux-libc-dev:i386
      - name: 进行安装后的清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: 构建自定义文件结构
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          git clone https://github.com/tty228/luci-app-serverchan
          git clone https://github.com/rosywrt/luci-theme-rosy
          git clone https://github.com/jefferymvp/luci-app-koolproxyR
          
      - name: 构建编译扩展环境
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 导入自定义配置
        run: |
          rm -f ./.config*
          touch ./.config
          
          # 编译32位x86固件:
          
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_generic=y
          CONFIG_TARGET_x86_generic_Generic=y
          CONFIG_ARIA2_BITTORRENT=y
          CONFIG_ARIA2_NOXML=y
          CONFIG_ARIA2_OPENSSL=y
          CONFIG_ARIA2_WEBSOCKET=y
          # CONFIG_DRIVER_11AC_SUPPORT is not set
          # CONFIG_DRIVER_11N_SUPPORT is not set
          # CONFIG_DRIVER_11W_SUPPORT is not set
          CONFIG_PACKAGE_6in4=y
          # CONFIG_PACKAGE_adbyby is not set
          CONFIG_PACKAGE_aria2=y
          CONFIG_PACKAGE_ariang=y
          # CONFIG_PACKAGE_ath9k-htc-firmware is not set
          CONFIG_PACKAGE_baidupcs-web=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-chrono=y
          CONFIG_PACKAGE_boost-random=y
          CONFIG_PACKAGE_boost-system=y
          # CONFIG_PACKAGE_coreutils-nohup is not set
          # CONFIG_PACKAGE_ddns-scripts is not set
          # CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          # CONFIG_PACKAGE_ddns-scripts_dnspod is not set
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_hd-idle=y
          # CONFIG_PACKAGE_hostapd-common is not set
          CONFIG_PACKAGE_icu=y
          CONFIG_PACKAGE_ip6tables=y
          # CONFIG_PACKAGE_iptables-mod-ipsec is not set
          CONFIG_PACKAGE_ipv6helper=y
          # CONFIG_PACKAGE_iw is not set
          # CONFIG_PACKAGE_kmod-ath is not set
          # CONFIG_PACKAGE_kmod-ath10k is not set
          # CONFIG_PACKAGE_kmod-ath5k is not set
          # CONFIG_PACKAGE_kmod-ath9k is not set
          # CONFIG_PACKAGE_kmod-ath9k-htc is not set
          # CONFIG_PACKAGE_kmod-cfg80211 is not set
          # CONFIG_PACKAGE_kmod-crypto-cbc is not set
          # CONFIG_PACKAGE_kmod-crypto-deflate is not set
          # CONFIG_PACKAGE_kmod-crypto-des is not set
          # CONFIG_PACKAGE_kmod-crypto-echainiv is not set
          # CONFIG_PACKAGE_kmod-crypto-hmac is not set
          # CONFIG_PACKAGE_kmod-crypto-md5 is not set
          # CONFIG_PACKAGE_kmod-crypto-rng is not set
          # CONFIG_PACKAGE_kmod-crypto-sha256 is not set
          # CONFIG_PACKAGE_kmod-crypto-wq is not set
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          # CONFIG_PACKAGE_kmod-ipsec is not set
          # CONFIG_PACKAGE_kmod-ipt-ipsec is not set
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          # CONFIG_PACKAGE_kmod-iptunnel6 is not set
          # CONFIG_PACKAGE_kmod-mac80211 is not set
          # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
          CONFIG_PACKAGE_kmod-nf-nat6=y
          # CONFIG_PACKAGE_kmod-rt2800-usb is not set
          # CONFIG_PACKAGE_kmod-rt2x00-lib is not set
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-usb-ehci=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-uhci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libdb47=y
          CONFIG_PACKAGE_libdouble-conversion=y
          CONFIG_PACKAGE_libexif=y
          CONFIG_PACKAGE_libexpat=y
          CONFIG_PACKAGE_libffi=y
          CONFIG_PACKAGE_libffmpeg-audio-dec=y
          CONFIG_PACKAGE_libflac=y
          CONFIG_PACKAGE_libgdbm=y
          # CONFIG_PACKAGE_libgmp is not set
          CONFIG_PACKAGE_libid3tag=y
          CONFIG_PACKAGE_libjpeg=y
          CONFIG_PACKAGE_libogg=y
          CONFIG_PACKAGE_libpcre2-16=y
          CONFIG_PACKAGE_libsqlite3=y
          CONFIG_PACKAGE_libuv=y
          CONFIG_PACKAGE_libvorbis=y
          CONFIG_PACKAGE_libwebsockets-full=y
          CONFIG_PACKAGE_libxml2=y
          CONFIG_PACKAGE_libzstd=y
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-ddns is not set
          CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-v2ray-server is not set
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-minidlna-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qbittorrent-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_minidlna=y
          CONFIG_PACKAGE_nano=y
          # CONFIG_PACKAGE_nlbwmon is not set
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_python=y
          CONFIG_PACKAGE_python-base=y
          CONFIG_PACKAGE_python-codecs=y
          CONFIG_PACKAGE_python-compiler=y
          CONFIG_PACKAGE_python-ctypes=y
          CONFIG_PACKAGE_python-db=y
          CONFIG_PACKAGE_python-decimal=y
          CONFIG_PACKAGE_python-distutils=y
          CONFIG_PACKAGE_python-email=y
          CONFIG_PACKAGE_python-gdbm=y
          CONFIG_PACKAGE_python-light=y
          CONFIG_PACKAGE_python-logging=y
          CONFIG_PACKAGE_python-multiprocessing=y
          CONFIG_PACKAGE_python-ncurses=y
          CONFIG_PACKAGE_python-openssl=y
          CONFIG_PACKAGE_python-pydoc=y
          CONFIG_PACKAGE_python-sqlite3=y
          CONFIG_PACKAGE_python-unittest=y
          CONFIG_PACKAGE_python-xml=y
          CONFIG_PACKAGE_qBittorrent=y
          CONFIG_PACKAGE_qt5-core=y
          CONFIG_PACKAGE_qt5-network=y
          CONFIG_PACKAGE_qt5-xml=y
          CONFIG_PACKAGE_rblibtorrent=y
          # CONFIG_PACKAGE_rt2800-usb-firmware is not set
          # CONFIG_PACKAGE_strongswan is not set
          # CONFIG_PACKAGE_strongswan-charon is not set
          # CONFIG_PACKAGE_strongswan-ipsec is not set
          # CONFIG_PACKAGE_strongswan-minimal is not set
          # CONFIG_PACKAGE_strongswan-mod-aes is not set
          # CONFIG_PACKAGE_strongswan-mod-gmp is not set
          # CONFIG_PACKAGE_strongswan-mod-hmac is not set
          # CONFIG_PACKAGE_strongswan-mod-kernel-netlink is not set
          # CONFIG_PACKAGE_strongswan-mod-nonce is not set
          # CONFIG_PACKAGE_strongswan-mod-pubkey is not set
          # CONFIG_PACKAGE_strongswan-mod-random is not set
          # CONFIG_PACKAGE_strongswan-mod-sha1 is not set
          # CONFIG_PACKAGE_strongswan-mod-socket-default is not set
          # CONFIG_PACKAGE_strongswan-mod-stroke is not set
          # CONFIG_PACKAGE_strongswan-mod-updown is not set
          # CONFIG_PACKAGE_strongswan-mod-x509 is not set
          # CONFIG_PACKAGE_strongswan-mod-xauth-generic is not set
          # CONFIG_PACKAGE_strongswan-mod-xcbc is not set
          CONFIG_PACKAGE_ttyd=y
          # CONFIG_PACKAGE_wireless-regdb is not set
          # CONFIG_PACKAGE_wpad is not set
          CONFIG_SQLITE_FTS3=y
          CONFIG_SQLITE_RTREE=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=256
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          EOF
          
          # 额外软件和主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-rosy=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          CONFIG_PACKAGE_luci-app-koolproxyR=y
          CONFIG_PACKAGE_luci-app-serverchan=y
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: 下载编译所需源码
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: 进行固件编译
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          
      - name: 准备文件
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name : 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
